Scijava-ize fork of project
scijava/scijava-packages-rules pull request #1
Opened 2021-07-14 16:54 UTC by gselzer

This PR establishes the foundation of this plugin, making a couple of major changes to the original fork of https://github.com/andrena/no-package-cycles-enforcer-rule:
* Establishes `pom-scijava` as the parent POM
* Abstracts the "default" behavior of a package rule into [`AbstractPackageEnforcementRule`](https://github.com/scijava/scijava-packages-plugin/blob/init/src/main/java/org/scijava/packages/plugin/AbstractPackageEnforcementRule.java), making it easier to write new Package Rules.

TODO:
* [ ] Add copyright to files
* [ ] Add `README`
* [ ] Modularize project using JPMS - we might want to push this to its own issue. The main issue in doing this is https://github.com/codehaus-plexus/plexus-containers/issues/17, but this is fixable.

2021-07-20 20:52 UTC, gselzer commented
> Modularize project using JPMS - we might want to push this to its own issue. The main issue in doing this is plexus-container-default requires a Automatic-Module-Name entry codehaus-plexus/plexus-containers#17, but this is fixable.

I think we should ignore this issue. There isn't much reason to modularize the project as it's not a library to be used by other projects. Furthermore, despite the answers provided in the linked issue, the Maven Enforcer plugin API depends on `plexus-container-default` which makes this artifact hard to get rid of.

@hinerm what do you think?

2021-11-12 05:26 UTC, ctrueden requested changes
Looking carefully at this project, I'm wondering why we don't just roll it into the existing scijava-maven-plugin. That component already has enforcer rules, and this project just adds two more. It is nice to have all of our enforcer rules in one place. Given that the upstream project is built on Java 8, and we are not JPMSifying this project either, I think the code should slot nicely into scijava-maven-plugin, and then we can delete this repository.

@gselzer Let's discuss very soon, and we can reform this into a PR against scijava-maven-plugin instead if you agree.

2021-11-12 05:26 UTC, ctrueden commented on .travis.yml
> +  - oraclejdk11
Since this code is forked from a JDK8-compatible plugin... are we actually using any JDK11-specific things? If not, why not stick with JDK8?

2021-11-12 05:26 UTC, ctrueden commented on README.md
> +[Circular dependencies](https://en.wikipedia.org/wiki/Circular_dependency) are usually considered poor practice. To prevent circular dependencies, add the following `execution`:
We should be more specific here, describing what package cycles are, and that this rule specifically detects those. This is distinct from circular dependencies at the module/component level.

2021-11-12 05:26 UTC, ctrueden commented on README.md
> +Subpackage Dependence can throw a wrench into libraries wishing to follow the [Dependency Inversion principle](https://en.wikipedia.org/wiki/Dependency_inversion_principle). To prevent subpackage dep
We should give a concrete example of what subpackage dependence looks like.

2021-11-12 05:26 UTC, ctrueden commented on README.md
>  * For more information about package cycles, see ["The Acyclic Dependencies Principle" by Robert C. Martin (Page 6)](http://www.objectmentor.com/resources/articles/granularity.pdf).
This article link is defunct, and should be removed.

2021-11-12 05:26 UTC, ctrueden commented on README.md
> +* The original version by Daniel Seidewitz on [Stackoverflow](http://stackoverflow.com/questions/3416547/maven-jdepend-fail-build-with-cycles). Improved by showing all packages afflicted with cycles
I'd like to split this bullet into two bullets: the first linking to the forked no-package-cycles-enforcer-rule project, and the second linking to the original version from SO.

2021-11-12 05:26 UTC, ctrueden commented on pom.xml
> -    </developers>
We shouldn't just delete these guys. They belong in the contributors section, because they _did_ write (a version of) this code, but are not responsible for maintaining it in its current incarnation.

2021-11-12 05:26 UTC, ctrueden commented on pom.xml
> +			<archive>https://forum.image.sc/tags/scijava-packages-rules</archive>
Discourse now uses `/tag/`, not `/tags/`, for linking to a tag.

2021-11-12 05:26 UTC, ctrueden commented on pom.xml
> +		<system>Travis CI</system>
Using GitHub Issues now, not Travis CI anymore.

2021-11-19 18:24 UTC, ctrueden commented
Merged into the scijava-maven-plugin as scijava/scijava-maven-plugin@8f5fa90ee05b0eca3223564792d4b2c047b79310. So this PR is now obsolete.

2021-11-19 18:24 UTC, closed without merging